name = "ai-skye-next"
compatibility_date = "2024-09-25"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"


[vars]
APP_NAME = "KontenKilat.id"
NEXT_PUBLIC_APP_KEY = "skye_ai_saas_public_app_key"

