name: AI SKYE CI

on:
  push:
    branches:
      - development
      - production
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  development:
    runs-on: ubuntu-latest
    environment: "production"
    env:
      NEXT_FIREBASE_API_KEY: ${{ secrets.NEXT_FIREBASE_API_KEY }}
      NEXT_FIREBASE_AUTH_DOMAIN: ${{ secrets.NEXT_FIREBASE_AUTH_DOMAIN }}
      NEXT_FIREBASE_PROJECT_ID: ${{ secrets.NEXT_FIREBASE_PROJECT_ID }}
      NEXT_FIREBASE_STORAGE_BUCKET: ${{ secrets.NEXT_FIREBASE_STORAGE_BUCKET }}
      NEXT_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.NEXT_FIREBASE_MESSAGING_SENDER_ID }}
      NEXT_FIREBASE_APP_ID: ${{ secrets.NEXT_FIREBASE_APP_ID }}
    steps:
      - name: Check internet connection
        run: |
          ping -c 4 google.com

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: "latest"

      # Cache node_modules
      - run: bun install --frozen-lockfile

      - run: bun --bun --base=origin/dev run lint
      - run: bun --bun --base=origin/production run lint

      - run: bun --bun --base=origin/dev run build
      - run: bun --bun --base=origin/production run build
