name: AI SKYE CI

on:
  push:
    branches:
      - development
      - production
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  development:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: "latest"

      # Cache node_modules
      - run: bun install --frozen-lockfile

      - run: bun --bun --base=origin/dev run lint
      - run: bun --bun --base=origin/production run lint

      - run: bun --bun --base=origin/dev run build
      - run: bun --bun --base=origin/production run build
